services:
  php:
    build:
      context: ./docker/
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    volumes:
      - ./application/:/var/www/html/
      - ./application/xdebug/:/var/www/html/xdebug/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf

  nginx:
    image: nginx:latest
    depends_on:
      - php
      - mysql
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./application/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
